language: c

dist: bionic

addons:
    apt:
        sources:
          - sourceline: 'ppa:vala-team'
        packages:
            - valac
            - libgee-0.8-dev
            - libgtk-3-dev
            - libgstreamer1.0-dev
            - libgstreamer-plugins-base1.0-dev
            - libgstreamer-plugins-good1.0-dev
            - ninja-build
            - meson

script:
    - mkdir builddir
    - meson ./ ./builddir
    - ninja -C builddir
    - ninja -C builddir test
