name: Building
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-20.04
    steps:
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: >-
          sudo apt-get update

          sudo apt-get install -y libgee-0.8-dev
          libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev
          libgstreamer1.0-dev libgtk-3-dev libgudev-1.0-dev meson ninja-build
          valac
      - uses: actions/checkout@v2
      - run: mkdir builddir
      - run: meson ./builddir
      - run: ninja -C builddir
      - run: ninja -C builddir test
